changelog:
  exclude:
    labels:
      - duplicate
      - invalid
      - wontfix
  categories:
    - title: New features
      labels:
        - enhancement
    - title: Bug fixes
      labels:
        - bug
    - title: Dependencies
      labels:
        - dependencies
    - title: CI and automation
      labels:
        - github_actions
    - title: Documentation
      labels:
        - documentation
    - title: Other changes
      labels:
        - "*"
